name: V4检测

on:
  schedule:
    - cron: '10 */12 * * *'        #这里更改自动运行的时间，没这两行的话只能手动运行
  workflow_dispatch:
    分支:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install requests
      - name: Install dependencies
        run: pip install tqdm opencv-python

      - name: Run iptv
        run: python ${{ github.workspace }}/IPTV/V4检测.py      #这里更改要运行的py

      - name: Run iptv
        run: python ${{ github.workspace }}/IPTV/分类去重.py      #这里更改要运行的py
        

      - name: 提交更改
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "Add generated file"
          git pull --rebase
          git push -f
